### ISSUE TITLE
i am genuinely so confused

### ISSUE THREAD

**Issue by sweetbabycarrots98** [ToTheMax/Snapchat-All-Memories-Downloader#103]
i am not a tech savvy person in any way, especially not with code. i have no idea what to do to get this working.  im so afraid of losing my snap memories! :( 

i dont understand what run locally means or how to get that working. i did the steps before that just fine. how do i install the required modules and run the script???

**Comment by ToTheMax** [comment]
Hey, I just updated the script, now works on Python, which might be easier to setup. Could you give it another try?

**Comment by fredystar200** [comment]
I think he will still get lost, here's how to use it :

## 📸 How to Use Snapchat All Memories Downloader :

### 1. Get Your Data

Follow the instructions here to download your Snapchat data export:
➡️ [Snapchat-All-Memories-Downloader Guide](https://github.com/ToTheMax/Snapchat-All-Memories-Downloader)

---

### 2. Download the Repository

Download the latest version of the project:
📦 [Download ZIP](https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/archive/refs/heads/main.zip)
---

### 3. Extract the Files

* Extract both **mydata~.zip** (your Snapchat data) and **Snapchat-All-Memories-Downloader-main.zip** into **separate folders** using [7-Zip](https://www.7-zip.org/) or any other extraction tool
* Move all the files from the `Snapchat-All-Memories-Downloader-main` folder (you’ll see files like `main.py`, `requirements.txt`, etc.) into your **mydata** folder (you will see `json folder`, `html folder`, `index.html`)

---

### 4. Open a Terminal in the `mydata` Folder

* Hold **Shift** and **Right-click** inside the folder
* Choose **“Open PowerShell window here”**
or
* In the address bar, type `cmd` and press **Enter** to open Command Prompt

---

### 5. Install Python Requirements

Make sure **Python** is installed on your system. ➡️ [Download here](https://www.python.org/downloads/)
Then, install all required packages by running:

```
pip install -r requirements.txt
```

---

### 6. Run the Script

Once the dependencies are installed, run the script with:

```
python main.py
```

---

### ✅ Done!

Your Snapchat memories will start downloading automatically.
You will see Downloading:

---

**Comment by GreenWoodLion** [comment]
I'm getting an error when trying to run the pip- install command.  Screen shot below, anyway you can help me out please?

<img width="1267" height="740" alt="Image" src="https://github.com/user-attachments/assets/d07250a8-4dee-4ff3-85bb-f1d955f05149" />
<img width="1115" height="629" alt="Image" src="https://github.com/user-attachments/assets/bf22db6a-d1d4-4b19-817b-93567a3795f7" />

**Comment by fredystar200** [comment]
Download python here : https://www.python.org/ftp/python/3.13.9/python-3.13.9-amd64.exe
Launch it and make sure to check Add Python to Path, then try again, 
If you already installed you can just modify and add it, but I recommend to uninstall and do it again

**Comment by sweetbabycarrots98** [comment]
thanks guys!! been very sick with the flu so haven't tried it yet. 
will try this weekend and update.
appreciate it :)

**Comment by FLJeepher** [comment]
this worked great except I always put words on my snaps. i.e. the temperature, what the scene is , or details on what is happening.  the script downloaded everything but none of the text is present.  ideas?

**Comment by mcuashley** [comment]
I tried this and it says "URL is missing an 'http://' or 'https://' protocol."

<img width="735" height="216" alt="Image" src="https://github.com/user-attachments/assets/e0ca9a7e-402f-4053-9e57-fa300a593413" />
